# Generated by Django 4.1.7 on 2023-02-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="primaryflat",
            options={"ordering": ["increase_procent"]},
        ),
        migrations.AlterModelOptions(
            name="secondaryflat",
            options={"ordering": ["marker"]},
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="author",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="district",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="floor_count",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="price_per_m2",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="residential_complex",
        ),
        migrations.RemoveField(
            model_name="secondaryflat",
            name="street",
        ),
        migrations.AddField(
            model_name="secondaryflat",
            name="diff",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondaryflat",
            name="kitchen_meters",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondaryflat",
            name="living_meters",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondaryflat",
            name="marker",
            field=models.CharField(
                choices=[("underpriced", "Underpriced"), ("overpriced", "Overpriced")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondaryflat",
            name="pred_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="secondaryflat",
            name="year_of_construction",
            field=models.IntegerField(null=True),
        ),
    ]
